services:
  app:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/var/www/html'
    networks:
      - nest
    depends_on:
      - mysql
  mysql:
    image: mysql:8
    ports:
      - '3306:3307'
    networks:
      - nest
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'grupo_adriano_cobuccio'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - nest-mysql:/var/lib/mysql
networks:
  nest:
    driver: bridge
volumes:
  nest-mysql:
    driver: local